# This file created by conda-build 2.0.4
# meta.yaml template originally from:
# /vagrant/recipes/condabuilder.lcpEpP, last modified Fri Oct  7 11:00:58 2016
# ------------------------------------------------

package:
    name: libcroco
    version: "0.6.12"
source:
    fn: libcroco-0.6.12.tar.xz
    sha256: ddc4b5546c9fb4280a5017e2707fbd4839034ed1aba5b7d4372212f34f84f860
    url: http://ftp.gnome.org/pub/gnome/sources/libcroco/0.6/libcroco-0.6.12.tar.xz
build:
    detect_binary_files_with_prefix: 'true'
    number: '1'
    script_env:
        - NJOBS
requirements:
    build:
        - glib
        - libxml2
    run:
        - glib
        - libxml2
about:
    home: http://www.linuxfromscratch.org/blfs/view/svn/general/libcroco.html
    license: LGPL
    summary: a standalone CSS2 parsing and manipulation library
