package:
  name: dstat-interface
  version: "1.4.3"

source:
  fn: dstat_interface-1.4.3-1.tar.gz
  url: https://pypi.python.org/packages/55/c5/4e624e48eb5c0f5ff164c39ae40fbee6555f0b4f8c9401d6c8934d2c0d28/dstat_interface-1.4.3-1.tar.gz
  md5: 9019563816d4698b5c987ebc129a0cad

requirements:
    build:
        - python
    run:
        - python
        - pyserial >=3.2
        - seaborn
        - numpy
        - scipy
        - matplotlib
        - pandas
        - pyyaml
        - pyzmq
        - zmq-plugin
about:
    home: http://microfluidics.utoronto.ca/dstat
    license: GPLv3
    summary: Interface software for DStat Potentiostat.
