package:
    name: dstat-interface-deps
    version: "1.1"
requirements:
    run:
        - gobject-introspection
        - gtk3
        - pygobject3
        - adwaita-icon-theme
        - dfu-programmer

about:
    home: http://microfluidics.utoronto.ca/dstat
    license: GPLv3
    summary: Binary dependencies for dstat-interface.