# This file created by conda-build 2.0.3
# meta.yaml template originally from:
# /vagrant/recipes/condabuilder.KHFb8G, last modified Wed Oct  5 11:37:19 2016
# ------------------------------------------------

package:
    name: dbus-client
    version: 1.10.18
source:
    fn: dbus-1.10.18.tar.gz
    patches:
        - skip-extras.patch
    sha256: 6049ddd5f3f3e2618f615f1faeda0a115104423a7996b7aa73e2f36e38cc514a
    url: https://dbus.freedesktop.org/releases/dbus/dbus-1.10.18.tar.gz
build:
    detect_binary_files_with_prefix: 'true'
    number: '0'
    script_env:
        - NJOBS
requirements:
    build:
        - python
about:
    home: http://dbus.freedesktop.org/
    license: LGPL
