# This file created by conda-build 2.0.3
# meta.yaml template originally from:
# /vagrant/recipes/condabuilder.BBWAIM, last modified Thu Oct  6 11:16:21 2016
# ------------------------------------------------

package:
    name: harfbuzz
    version: 1.4.6
source:
    fn: harfbuzz-1.4.6.tar.bz2
    sha256: 21a78b81cd20cbffdb04b59ac7edfb410e42141869f637ae1d6778e74928d293
    url: https://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.4.6.tar.bz2
build:
    detect_binary_files_with_prefix: 'true'
    number: '3'
    script_env:
        - NJOBS
requirements:
    build:
        - freetype
        - pcre
        - glib
        - gobject-introspection
        - icu
        - python
    run:
        - freetype
        - glib
        - gobject-introspection
        - icu
about:
    home: http://www.freedesktop.org/wiki/Software/HarfBuzz/
    license: MIT
    summary: An OpenType text shaping engine.
