# This file created by conda-build 2.0.3
# meta.yaml template originally from:
# /vagrant/recipes/condabuilder.Bya11R, last modified Thu Oct  6 14:27:29 2016
# ------------------------------------------------

package:
    name: pixman
    version: 0.34.0
source:
    fn: pixman-0.34.0.tar.gz
    sha256: 21b6b249b51c6800dc9553b65106e1e37d0e25df942c90531d4c3997aa20a88e
    url: https://cairographics.org/releases/pixman-0.34.0.tar.gz
build:
    detect_binary_files_with_prefix: 'true'
    number: '1'
    script_env:
        - NJOBS
requirements:
    build: ''
about:
    home: http://www.pixman.org/
    license: MIT
    summary: A low-level software library for pixel manipulation
