# This file created by conda-build 2.0.4
# meta.yaml template originally from:
# /vagrant/recipes/condabuilder.ftK0iG, last modified Fri Oct  7 11:00:45 2016
# ------------------------------------------------

package:
    name: librsvg
    version: "2.40.17"
source:
    fn: librsvg-2.40.17.tar.xz
    sha256: e6f6c5cbecc405bb945c7cd15061276035ae3173bbb3bb25e8a916779c7f69cc
    url: https://download.gnome.org/sources/librsvg/2.40/librsvg-2.40.17.tar.xz
build:
    detect_binary_files_with_prefix: 'true'
    number: '1'
    script_env:
        - NJOBS
requirements:
    build:
        - cairo-gobject
        - gdk-pixbuf
        - glib
        - libcroco
        - libxml2
        - pango >=1.38.1
        - python
    run:
        - cairo-gobject
        - gdk-pixbuf
        - glib
        - libcroco
        - libxml2
        - pango >=1.38.1
about:
    home: https://wiki.gnome.org/Projects/LibRsvg
    license: LGPL
    summary: a library to render SVG files using Cairo

